# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7556768f2db2685d3d42979e4ca2a040f62d9b255e10d0a52cf15202590adcd46f176198576f935ed9a80fa324367dcba49eeab06782c3e1af2499ae7833d49

test:
  secret_key_base: 1fbc8713d9ae76119e62798797a968d76934da5ca3e5c8b75cef582f9f355c244ba5840c5859921080c16e4d619c6e3581c68b8e8b0c718d4a4b19bd353674df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
